// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awkutipunynsfqiiresk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3a3V0aXB1bnluc2ZxaWlyZXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNjczNDcsImV4cCI6MjA1NTY0MzM0N30.0CKIPtzsJHAjm2VVYqRpRbl5qO73CLC3XmvGgF-cgHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);